# -*- coding: utf-8 -*-
"""binocular

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15paEIfZge0CQYb2ikgd1JkfQ2GRZRQ-m
"""

git clone https://github.com/JetsonHacksNano/CSI-Camera.git
cd CSI-Camera
gst-launch-1.0 nvarguscamerasrc sensor_id=0 ! 'video/x-raw(memory:NVMM),width=3280, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=2 ! 'video/x-raw, width=816, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e